name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
#run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run : echo Hello Omerlab
      - run : cat /etc/os*
   
